# Constructors ====
# Currently supports [Seurat::FindAllMarkers()] return
.seuratMarkers <- function(df) {
    df %>%
        as.data.frame %>%
        remove_rownames %>%
        as("tibble") %>%
        camel %>%
        rename(symbol = .data[["gene"]]) %>%
        tidy_select(c("cluster", "symbol"), everything()) %>%
        group_by(.data[["cluster"]])
}



# Methods ====
#' Top Markers
#'
#' @rdname topMarkers
#'
#' @param n Number of genes per cluster.
#' @param show Show [kable].
#'
#' @return [tibble].
#' @export
setMethod("topMarkers", "data.frame", function(object, n = 4L, show = TRUE) {
    markers <- .seuratMarkers(object) %>%
        top_n(n = n, wt = .data[["avgDiff"]])
    if (isTRUE(show)) {
        kable(markers,
              caption = paste("Top", n, "markers per cluster")) %>% show
    }
    markers
})



#' Known Markers Detected
#'
#' @rdname knownMarkersDetected
#'
#' @param x All markers [data.frame] generated by
#'   [Seurat::FindAllMarkers()].
#' @param y Known markers imported by [readKnownMarkers()].
#' @param show Show [kable].
#'
#' @return [tibble].
#' @export
setMethod(
    "knownMarkersDetected",
    signature(x = "data.frame", y = "tbl_df"),
    function(x, y, show = TRUE) {
        markers <- .seuratMarkers(x) %>%
            left_join(y, by = "symbol") %>%
            filter(!is.na(.data[["cellType"]]))
        if (isTRUE(show)) {
            kable(markers, caption = "Known markers detected") %>% show
        }
        markers
    })
