#' Known Markers Detected
#'
#' @rdname knownMarkersDetected
#' @name knownMarkersDetected
#'
#' @param object All markers [data.frame] generated by
#'   [Seurat::FindAllMarkers()].
#' @param knownMarkers Known markers imported by [readMarkers()].
#' @param show Show [kable].
#'
#' @return [tibble].
NULL



# Constructors ====
.knownMarkersDetected <- function(object, knownMarkers, show = FALSE) {
    markers <- .groupMarkers(object) %>%
        left_join(knownMarkers[, c("cell", "ensgene")],
                  by = "ensgene") %>%
        tidy_select(c("cell", "ensgene", "symbol", "cluster"),
                    everything()) %>%
        tidy_filter(!is.na(.data[["cell"]])) %>%
        .[order(.[["cell"]],
                .[["symbol"]],
                .[["pvalue"]],
                .[["avgDiff"]],
                decreasing = c(FALSE, FALSE, FALSE, TRUE)), ] %>%
        group_by(!!sym("cell"))
    if (isTRUE(show)) {
        .markersKable(markers, caption = "Known markers detected")
    }
    markers
}



# Methods ====
#' @rdname knownMarkersDetected
#' @export
setMethod(
    "knownMarkersDetected",
    signature(object = "data.frame", knownMarkers = "tbl_df"),
    .knownMarkersDetected)
