#' Select samples
#'
#' @details Internally, pattern matching against sample and file names is
#'   applied using [str_detect()].
#'
#' @note Supports an object containing filtered counts generated by
#'   [filter_barcodes()] on a [bcbioSCDataSet].
#'
#' @rdname select_samples
#'
#' @param object Primary object.
#' @param ... Columns to use for grep pattern matching. Supply a named character
#'   vector containing the column name and the grep pattern.
#'
#' @return [SCSubset].



#' @rdname select_samples
#' @usage NULL
.select_samples <- function(object, ...) {
    sample_metadata <- sample_metadata(object)
    patterns <- c(...)
    list <- lapply(seq_along(patterns), function(a) {
        sample_metadata %>%
            filter(str_detect(.data[[names(patterns)[[a]]]], patterns[[a]])) %>%
            pull("sample_id") %>%
            unique %>%
            sort
    })
    sample_ids <- Reduce(intersect, list) %>% sort
    if (!length(sample_ids)) {
        stop("No samples matched")
    }
    message(paste(length(sample_ids),
                  "samples matched:",
                  toString(sample_ids)))
    sample_metadata <- sample_metadata %>%
        filter(.data[["sample_id"]] %in% sample_ids)

    # Match the sample ID prefix in the cellular barcode columns of the matrix.
    # Here "cb" is short for "cellular barcodes".
    cb_pattern <- sample_ids %>%
        str_c(collapse = "|") %>%
        str_c("^(", ., ")_")
    cb_matches <- colnames(object) %>% .[str_detect(., cb_pattern)]
    if (!length(cb_matches)) {
        stop("No cellular barcodes matched")
    }
    message(paste(length(cb_matches), "cellular barcodes"))

    # Return the SCSubset object
    sparse_counts <- assay(object)[, cb_matches]
    col_data <- colData(object)[cb_matches, ]
    row_data <- .row_data(object)
    metadata <- metadata(object)
    metadata[["sample_metadata"]] <- sample_metadata
    se <- .summarized_experiment(
        assays = SimpleList(
            sparse_counts = sparse_counts),
        col_data = col_data,
        row_data = row_data,
        metadata = metadata)
    new("SCSubset", se)
}



#' @rdname select_samples
#' @export
setMethod("select_samples", "bcbioSCDataSet", .select_samples)

#' @rdname select_samples
#' @export
setMethod("select_samples", "SCSubset", .select_samples)
