# Currently supports [Seurat::FindAllMarkers()] return
.seurat_markers <- function(df) {
    df %>%
        remove_rownames %>%
        as("tibble") %>%
        snake %>%
        rename(symbol = .data[["gene"]]) %>%
        tidy_select(c("cluster", "symbol"), everything()) %>%
        group_by(.data[["cluster"]])
}



#' Top markers
#'
#' @rdname top_markers
#'
#' @param object Object.
#' @param n Number of genes per cluster.
#' @param show Show [kable].
#'
#' @return [tibble].
#' @export
setMethod("top_markers", "data.frame", function(object, n = 4L, show = TRUE) {
    markers <- .seurat_markers(object) %>%
        top_n(n = n, wt = .data[["avg_diff"]])
    if (isTRUE(show)) {
        kable(markers,
              caption = paste("Top", n, "markers per cluster")) %>%
            asis_output %>%
            show
    }
    markers
})



#' Known markers detected
#'
#' @rdname known_markers_detected
#'
#' @param x All markers [data.frame] generated by
#'   [Seurat::FindAllMarkers()].
#' @param y Known markers imported by [read_known_markers()].
#' @param show Show [kable].
#'
#' @return [tibble].
#' @export
setMethod(
    "known_markers_detected",
    signature(x = "data.frame", y = "tbl_df"),
    function(x, y, show = TRUE) {
        markers <- .seurat_markers(x) %>%
            left_join(y, by = "symbol") %>%
            filter(!is.na(cell_type))
        if (isTRUE(show)) {
            kable(markers, caption = "Known markers detected") %>%
                asis_output %>%
                show
        }
        markers
    })
