#' Select samples
#'
#' @details Internally, pattern matching against sample and file names is
#'   applied using [str_detect()].
#'
#' @note Currently supports a [SummarizedExperiment] containing filtered counts
#'   generated by [filter_barcodes()] on a [bcbioSCDataSet].
#'
#' @rdname select_samples
#'
#' @param object Primary object.
#' @param sample_name Character vector of sample names.
#' @param file_name Character vector of file names.
#'
#' @return [SummarizedExperiment].



#' @rdname select_samples
#' @usage NULL
#' @export
setMethod("select_samples", "bcbioSCDataSet", function(object) {
    stop(paste(
        "Sample extraction using `select_samples()` can only be performed",
        "after barcode filtering. Run `filter_barcodes()` first on the",
        "bcbioSCDataSet."))
})



#' @rdname select_samples
#' @export
setMethod("select_samples", "SummarizedExperiment", function(
    object,
    sample_name = NULL,
    file_name = NULL) {
    sample_metadata <- sample_metadata(object)

    # Filter metadata by sample name
    if (!is.null(sample_name)) {
        sample_name_pattern <- str_c(sample_name, collapse = "|")
        sample_metadata <- sample_metadata %>%
            filter(str_detect(.data[["sample_name"]], sample_name_pattern))
    }

    # Filter metadata by file name
    if (!is.null(file_name)) {
        file_name_pattern <- str_c(file_name, collapse = "|")
        sample_metadata <- sample_metadata %>%
            filter(str_detect(.data[["file_name"]], file_name_pattern))
    }

    if (!nrow(sample_metadata)) {
        stop("No matching samples")
    }

    sample_id_pattern <- sample_metadata[["sample_id"]] %>%
        str_c(collapse = "|") %>%
        str_c("^(", ., ")\\:")
    cellular_barcodes <- colnames(object) %>%
        .[str_detect(., sample_id_pattern)]

    # Counts ====
    sparse_counts <- assay(object)[, cellular_barcodes]

    # colData ====
    col_data <- colData(object)[cellular_barcodes, ]

    # rowData ====
    row_data <- .row_data(object)

    # Metadata ====
    metadata <- metadata(object)
    metadata[["sample_metadata"]] <- sample_metadata

    .summarized_experiment(
        sparse_counts = sparse_counts,
        col_data = col_data,
        row_data = row_data,
        metadata = metadata)
})
