#' Plot clusters
#'
#' @param seurat [seurat].
#' @param genes Genes.
#'
#' @return [ggplot].
#' @export
plot_clusters <- function(seurat, genes) {
    VlnPlot(
        seurat,
        features.plot = genes,
        use.scaled = TRUE)
    FeaturePlot(
        seurat,
        features.plot = genes,
        cols.use = c("grey", "blue"))
}



#' Top marker genes
#'
#' @param markers Markers.
#' @param n Number of genes per cluster.
#'
#' @return [data.frame].
#' @export
top_markers <- function(markers, n = 4L) {
    markers %>%
        group_by(.data[["cluster"]]) %>%
        top_n(n = n, wt = .data[["avg_diff"]])
}



#' Plot known markers
#'
#' @param seurat [seurat].
#' @param known_markers_detected Known markers detected [data.frame].
#'
#' @export
plot_known_markers <- function(seurat, known_markers_detected) {
    cell_type <- known_markers_detected %>% pull("cell_type") %>% unique
    pblapply(seq_along(cell_type), function(a) {
        genes <- known_markers_detected %>%
            filter(.data[["cell_type"]] == cell_type[a]) %>%
            pull("gene") %>%
            unique %>%
            sort
        plot_clusters(seurat, genes)
    }) %>%
        invisible
}



#' Plot top markers
#'
#' @param seurat [seurat].
#' @param top_markers Top markers [data.frame] generated by [top_markers()].
#'
#' @return [ggplot].
#' @export
plot_top_markers <- function(seurat, top_markers) {
    pblapply(levels(top_markers[["cluster"]]), function(a) {
        genes <- top_markers %>%
            filter(.data[["cluster"]] == a) %>%
            pull("gene")
        plot_clusters(seurat, genes)
    }) %>%
        invisible
}
